name: manual-image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        type: string
        default: 'master'
      image_tag:
        description: 'Tag suffix (usually branch name or feature name, no slashes)'
        required: true
        type: string
        default: 'dev'

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and push tag
        run: |
          # Create a tag like v0.0.0-dev-feature-name
          TAG="v0.0.0-dev-${{ github.event.inputs.image_tag }}"
          git tag $TAG
          git push origin $TAG 